FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04

# Setup
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY .dockerignore ./app/.dockerignore
COPY ./ /app/
